In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

In [4]:
df = pd.read_csv("cust_seg - 1655553015951.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   custid               200 non-null    int64
 1   sex                  200 non-null    int64
 2   AqChannel            200 non-null    int64
 3   region               200 non-null    int64
 4   Marital_status       200 non-null    int64
 5   segment              200 non-null    int64
 6   pre_usage            200 non-null    int64
 7   Post_usage_1month    200 non-null    int64
 8   Latest_mon_usage     200 non-null    float64
 9   post_usage_2ndmonth  200 non-null    float64
dtypes: float64(2), int64(8)
memory usage: 15.8 KB

In [6]:
df.describe()

,custid,sex,AqChannel,region,Marital_status,segment,pre_usage,Post_usage_1month,Latest_mon_usage,post_usage_2ndmonth
count,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,100.500000,0.54500,3.430000,2.055000,1.160000,2.025000,52.230000,52.775000,63.174000,58.052500
std,57.879185,0.49922,1.039472,0.724291,0.367526,0.690477,10.252937,9.478586,11.242137,10.426445
min,1.000000,0.00000,1.000000,1.000000,1.000000,1.000000,28.000000,31.000000,39.600000,34.100000
25%,50.750000,0.00000,3.000000,2.000000,1.000000,2.000000,44.000000,45.750000,54.000000,50.325000
50%,100.500000,1.00000,4.000000,2.000000,1.000000,2.000000,50.000000,54.000000,62.400000,59.400000
75%,150.250000,1.00000,4.000000,3.000000,1.000000,2.250000,60.000000,60.000000,70.800000,66.000000
max,200.000000,1.00000,4.000000,3.000000,2.000000,3.000000,76.000000,67.000000,90.000000,73.700000

In [7]:
df.head()

,custid,sex,AqChannel,region,Marital_status,segment,pre_usage,Post_usage_1month,Latest_mon_usage,post_usage_2ndmonth
0,70,0,4,1,1,1,57,52,49.2,57.2
1,121,1,4,2,1,3,68,59,63.6,64.9
2,86,0,4,3,1,1,44,33,64.8,36.3
3,141,0,4,3,1,3,63,44,56.4,48.4
4,172,0,4,2,1,2,47,52,68.4,57.2

In [10]:
# Q6. Applying pearson's correlation

#H0: There is no relationship between latest mon usage and pre usage
#Ha: There is a relationship between latest mon usage and pre usage

alpha = 0.05

statistic,p_value = stats.pearsonr(df.pre_usage, df.Latest_mon_usage)

In [13]:
if p_value < alpha:
    print('reject the null hypothesis; There is a relationship between latest mon usage and pre usage')
else:
    print('fail to reject the null hypothesis; There is no relationship between latest mon usage and pre usage')

reject the null hypothesis; There is a relationship between latest mon usage and pre usage

In [ ]:
# Q4. ANOVA test
# H0: No difference in credit card usage of three different segments
# Ha: There is a difference in credit card usage of three different segments

array([1, 3, 2])

In [15]:
var = 'pre_usage'
seg1 = df.loc[df.segment == 1, var]
seg2 = df.loc[df.segment == 2, var]
seg3 = df.loc[df.segment == 3, var]

In [ ]:
statistic, p_value = stats.f_oneway(seg1, seg2, seg3)

F_onewayResult(statistic=np.float64(21.28234763340855), pvalue=np.float64(4.283274139124812e-09))

In [18]:
if p_value < alpha:
    print('reject the null hypothesis; There is a difference in credit card usage of three different segments')
else:
    print('fail to reject the null hypothesis; There is a difference in credit card usage of three different segments')

reject the null hypothesis; There is a difference in credit card usage of three different segments