# Summarizing Automobile Evaluation Data

In the following project you'll use what you've learned about summarizing categorical data to analyze a sample from a popular open source dataset. This dataset contains information on the cost and physical attributes of several thousand cars. Originally, this dataset was used to train a classification model that assigned an acceptability score/category to cars based on these attributes.

The car evaluation dataset has been sourced from the UCI Machine Learning Repository and has been slightly modified for this project. Specifically, one additional field `manufacturer_country` has been simulated for illustrative purposes. You can read more about the details, features, and original uses of this dataset in research on the [UCI data description page](https://archive.ics.uci.edu/ml/datasets/car+evaluation).

## Summarizing Manufacturing Country

1. `manufacturer_country` is a _nominal categorical variable_ that indicates the country of the manufacturer of each car reviewed. Create a table of frequencies of all the cars reviewed by `manufacturer_country`. What is the modal category? Which country appears 4th most frequently? Print out your results.

In [39]:
import pandas as pd

car_eval = pd.read_csv('car_eval_dataset.csv')
car_eval.head()

,buying_cost,maintenance_cost,doors,capacity,luggage,safety,acceptability,manufacturer_country
0,vhigh,low,4,4,small,med,unacc,China
1,vhigh,med,3,4,small,high,acc,France
2,med,high,3,2,med,high,unacc,United States
3,low,med,4,more,big,low,unacc,United States
4,low,high,2,more,med,high,acc,South Korea

In [3]:
car_eval.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   buying_cost           1000 non-null   object
 1   maintenance_cost      1000 non-null   object
 2   doors                 1000 non-null   object
 3   capacity              1000 non-null   object
 4   luggage               1000 non-null   object
 5   safety                1000 non-null   object
 6   acceptability         1000 non-null   object
 7   manufacturer_country  1000 non-null   object
dtypes: object(8)
memory usage: 62.6+ KB

In [12]:
car_eval.groupby('manufacturer_country').manufacturer_country.count().sort_values(ascending=False)

manufacturer_country
Japan            228
Germany          218
South Korea      159
United States    138
Italy             97
France            87
China             73
Name: manufacturer_country, dtype: int64

In [23]:
car_eval.manufacturer_country.value_counts().index[3]

'United States'

2. Calculate a table of proportions for countries that appear in `manufacturer_country` in the dataset. What percentage of cars were manufactured in Japan?

In [28]:
temp = car_eval.manufacturer_country.value_counts(normalize=True).reset_index()
temp.loc[temp.manufacturer_country == 'Japan', 'proportion']

0    0.228
Name: proportion, dtype: float64

## Summarizing Buying Costs

3. `buying_cost` is a categorical variable which describes the cost of buying any car in the dataset. Print out a list of the possible values for this variable.

In [40]:
car_eval.buying_cost.unique()

array(['vhigh', 'med', 'low', 'high'], dtype=object)

4. `buying_cost` is an _ordinal categorical variable_, which means we can create an order associated with the values in the data and perform numeric operations on the variable. Create a new list, `buying_cost_categories`, that contains the unique values in `buying_cost`, ordered from lowest to highest.

In [41]:
buying_cost_categories = ['low', 'med', 'high', 'vhigh']
buying_cost_categories

['low', 'med', 'high', 'vhigh']

5. Convert `buying_cost` to type `'category'` using the list you created in the previous exercise.

In [58]:
# pd.Categorical

#car_eval['buying_cost'] = pd.Categorical(car_eval.buying_cost, categories=buying_cost_categories, ordered=True)
pd.Categorical(car_eval.buying_cost, categories=buying_cost_categories, ordered=True)

['vhigh', 'vhigh', 'med', 'low', 'low', ..., 'low', 'low', 'vhigh', 'low', 'low']
Length: 1000
Categories (4, object): ['low' < 'med' < 'high' < 'vhigh']

6. Calculate the median category of the `buying_cost` variable and print the result.

In [67]:
import numpy as np
median = np.median(car_eval.buying_cost.cat.codes)
buying_cost_categories[int(median)]

'med'

## Summarizing Luggage Capacity

7. `luggage` is a categorical variable in the car evaluations dataset that records the luggage capacity for each reviewed car. Calculate a table of proportions for this variable and print the result.

In [74]:
np.round(car_eval.luggage.value_counts(normalize=True) * 100, 2)

luggage
small    33.9
med      33.3
big      32.8
Name: proportion, dtype: float64

8. Are there any missing values in this column? Replicate the table of proportions from the previous exercise, but do not drop any missing values from the count. Print the result.

In [ ]:
car_eval.luggage.value_counts(normalize=True, dropna=False) # Helpful to see the breakdowns in missings

luggage
small    0.339
med      0.333
big      0.328
Name: proportion, dtype: float64

9. Without passing `normalize = True` to `.value_counts()`, can you replicate the result you got in the previous exercises?

In [ ]:
car_eval.luggage.value_counts() / car_eval.shape[0] # len() function is also a good candidate

1000

## Summarizing Passenger Capacity

10. `doors` is a categorical variable in the car evaluations dataset that records the count of doors for each reviewed car. Find the count of cars that have 5 or more doors. You can identify cars with 5+ doors by looking for cars that have a value of `'5more'` in the `doors` column. Print your result.

In [84]:
car_eval.loc[car_eval.doors=='5more', 'doors'].count()

np.int64(246)

In [87]:
temp = car_eval.doors.value_counts().reset_index()
temp[temp.doors == '5more']

   doors  count
2  5more    246

11. Find the proportion of cars that have 5+ doors and print the result.

In [88]:
car_eval.loc[car_eval.doors=='5more', 'doors'].count() / car_eval.shape[0]

np.float64(0.246)

In [89]:
temp = car_eval.doors.value_counts(normalize=True).reset_index()
temp[temp.doors == '5more']

   doors  proportion
2  5more       0.246

In [91]:
# Capture the proportion of cars by manufacturing country and buying cost

In [ ]:
# What's the median maintenace cost (ordinal categorial data) by luggage and safety

In [ ]:
# Identify the total cars excluding 5 or more doors in Japan and South Korea

In [ ]:
# Which country witnesses highest vs lowest maintenance cost?