In [1]:
pip list

Package                   Version
------------------------- --------------
altair                    5.5.0
anyio                     4.3.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
Babel                     2.15.0
beautifulsoup4            4.12.3
bleach                    6.1.0
blinker                   1.9.0
cachetools                5.5.2
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.8
colorama                  0.4.6
comm                      0.2.2
contourpy                 1.3.1
cycler                    0.12.1
dash                      2.18.2
dash-core-components      2.0.0
dash-html-components      2.0.0
dash-table                5.0.0
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
executing                 2.0.1
fastjsonschema            2.19.1
Flask                     3.0.3
fonttools                 4.56.0
fqdn                      1.5.1
frozendict                2.4.6
gitdb                     4.0.12
GitPython                 3.1.44
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.0
idna                      3.7
importlib_metadata        8.6.1
ipykernel                 6.29.4
ipython                   8.24.0
ipywidgets                8.1.2
isoduration               20.11.0
itsdangerous              2.2.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.5.2
json5                     0.9.25
jsonpointer               2.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            8.6.1
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.0
jupyter_server_terminals  0.5.3
jupyterlab                4.1.8
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.1
jupyterlab_widgets        3.0.10
kiwisolver                1.4.8
lxml                      5.3.1
MarkupSafe                2.1.5
matplotlib                3.10.0
matplotlib-inline         0.1.7
mistune                   3.0.2
multitasking              0.0.11
mysql-connector-python    9.2.0
narwhals                  1.27.1
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.1.3
notebook_shim             0.2.4
numpy                     2.2.2
overrides                 7.7.0
packaging                 24.0
pandas                    2.2.3
pandocfilters             1.5.1
parso                     0.8.4
patsy                     1.0.1
peewee                    3.17.9
pillow                    11.1.0
pip                       24.0
platformdirs              4.2.1
plotly                    6.0.0
prometheus_client         0.20.0
prompt-toolkit            3.0.43
protobuf                  5.29.4
psutil                    5.9.8
psycopg2                  2.9.10
pure-eval                 0.2.2
pyarrow                   19.0.1
pycparser                 2.22
pydeck                    0.9.1
Pygments                  2.18.0
pyparsing                 3.2.1
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pytz                      2025.1
pywin32                   306
pywinpty                  2.0.13
PyYAML                    6.0.1
pyzmq                     26.0.3
qtconsole                 5.5.2
QtPy                      2.4.1
referencing               0.35.1
requests                  2.31.0
retrying                  1.3.4
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.18.1
scikit-learn              1.7.2
scipy                     1.15.2
seaborn                   0.13.2
Send2Trash                1.8.3
setuptools                75.8.0
six                       1.16.0
smmap                     5.0.2
sniffio                   1.3.1
soupsieve                 2.5
stack-data                0.6.3
statsmodels               0.14.4
streamlit                 1.44.0
ta                        0.11.0
tabulate                  0.9.0
tenacity                  9.0.0
terminado                 0.18.1
threadpoolctl             3.6.0
tinycss2                  1.3.0
toml                      0.10.2
tornado                   6.4
traitlets                 5.14.3
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.2
tzdata                    2025.1
uri-template              1.3.0
urllib3                   2.2.1
watchdog                  6.0.0
wcwidth                   0.2.13
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.0.6
widgetsnbextension        4.0.10
yfinance                  0.2.55
zipp                      3.21.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy
import pandas
import matplotlib
import seaborn
import sklearn

In [3]:
import pandas as pd

df = pd.read_csv("file.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'file.csv'

In [ ]:
import os #Check your current working directory
os.getcwd()

'c:\\Users\\Noor Saba\\Dropbox\\PC\\Downloads\\Data Science with Python'

In [5]:
df = pd.read_csv(r"C:\Users\Noor Saba\Dropbox\PC\Downloads\Data Science with Python\stores.csv")

In [ ]:
df.head() #To view the first 5 rows of the dataframe

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2

In [7]:
df.head(10)
df.tail() #To view the last 5 rows of the dataframe

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
27,STR128,Super Market,Super Market,Kolkata,30.4,40,95.1,113,3.77,1.513,16.9,1,1,5,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.5,0,1,5,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.5,0,1,5,4
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.6,0,1,5,4
31,STR132,Digital Bazar,Electronincs,Kolkata,21.4,40,121.0,109,4.11,2.780,18.6,1,1,4,2

In [8]:
df.tail() #To view the last 5 rows of the dataframe

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
27,STR128,Super Market,Super Market,Kolkata,30.4,40,95.1,113,3.77,1.513,16.9,1,1,5,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.5,0,1,5,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.5,0,1,5,4
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.6,0,1,5,4
31,STR132,Digital Bazar,Electronincs,Kolkata,21.4,40,121.0,109,4.11,2.780,18.6,1,1,4,2

In [9]:
df #To view the entire dataframe

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2
5,STR106,Apparel Zone,Apparel,Delhi,18.1,60,225.0,105,2.76,3.460,20.22,1,0,3,1
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4
7,STR108,Digital Bazar,Electronincs,Delhi,24.4,40,146.7,62,3.69,3.190,20.00,1,0,4,2
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4
10,STR111,Super Bazar,Super Market,Chennai,17.8,60,167.6,123,3.92,3.440,18.90,1,0,4,4
11,STR112,Super Market,Super Market,Chennai,16.4,80,275.8,180,NaN,4.070,17.40,0,0,3,3
12,STR113,Central Store,Super Market,Chennai,17.3,80,275.8,180,NaN,3.730,17.60,0,0,3,3
13,STR114,Apparel Zone,Apparel,Chennai,15.2,80,275.8,180,NaN,3.780,18.00,0,0,3,3
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4
16,STR117,Electronics Zone,Electronincs,Mumbai,14.7,80,440.0,230,3.23,5.345,17.42,0,0,3,4
17,STR118,Apparel Zone,Apparel,Mumbai,32.4,40,78.7,66,4.08,2.200,19.47,1,1,4,1
18,STR119,Super Bazar,Super Market,Mumbai,30.4,40,75.7,52,4.93,1.615,18.52,1,1,4,2
19,STR120,Super Market,Super Market,Mumbai,33.9,40,71.1,65,4.22,1.835,19.90,1,1,4,1
20,STR121,Central Store,Super Market,Mumbai,21.5,40,120.1,97,3.70,2.465,20.01,1,0,3,1
21,STR122,Apparel Zone,Apparel,Mumbai,15.5,80,318.0,150,2.76,3.520,16.87,0,0,3,2
22,STR123,Fashion Bazar,Apparel,Mumbai,15.2,80,304.0,150,3.15,3.435,17.30,0,0,3,2
23,STR124,Digital Bazar,Electronincs,Mumbai,13.3,80,350.0,245,3.73,3.840,15.41,0,0,3,4
24,STR125,Electronics Zone,Electronincs,Kolkata,19.2,80,400.0,175,3.08,3.845,17.05,0,0,3,2
25,STR126,Apparel Zone,Apparel,Kolkata,27.3,40,79.0,66,4.08,1.935,18.90,1,1,4,1
26,STR127,Super Bazar,Super Market,Kolkata,26.0,40,120.3,91,4.43,2.140,16.70,0,1,5,2
27,STR128,Super Market,Super Market,Kolkata,30.4,40,95.1,113,3.77,1.513,16.90,1,1,5,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.50,0,1,5,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.50,0,1,5,4
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.60,0,1,5,4
31,STR132,Digital Bazar,Electronincs,Kolkata,21.4,40,121.0,109,4.11,2.780,18.60,1,1,4,2

In [10]:
df.shape #To view the shape of the dataframe (rows, columns)

(32, 15)

In [11]:
df.columns #To view the column names of the dataframe

Index(['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost',
       'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment'],
      dtype='object')

In [12]:
df.info() #To view a concise summary of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StoreCode        32 non-null     object
 1   StoreName        32 non-null     object
 2   StoreType        32 non-null     object
 3   Location         32 non-null     object
 4   OperatingCost    32 non-null     float64
 5   Staff_Cnt        32 non-null     int64
 6   TotalSales       32 non-null     float64
 7   Total_Customers  32 non-null     int64
 8   AcqCostPercust   29 non-null     float64
 9   BasketSize       32 non-null     float64
 10  ProfitPercust    32 non-null     float64
 11  OwnStore         32 non-null     int64
 12  OnlinePresence   32 non-null     int64
 13  Tenure           32 non-null     int64
 14  StoreSegment     32 non-null     int64
dtypes: float64(5), int64(6), object(4)
memory usage: 3.9+ KB

In [13]:
df.describe() #To view statistical summary of numerical columns

,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
count,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,20.090625,61.875000,230.721875,146.687500,3.651034,3.217250,17.848750,0.437500,0.406250,3.687500,2.625000
std,6.026948,17.859216,123.938694,68.562868,0.532664,0.978457,1.786943,0.504016,0.498991,0.737804,1.211504
min,10.400000,40.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.000000
25%,15.425000,40.000000,120.825000,96.500000,3.150000,2.581250,16.892500,0.000000,0.000000,3.000000,2.000000
50%,19.200000,60.000000,196.300000,123.000000,3.730000,3.325000,17.710000,0.000000,0.000000,4.000000,2.000000
75%,22.800000,80.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.000000
max,33.900000,80.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,4.000000